disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - shorthand_operator
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - force_try
  - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
